set -g default-shell /bin/zsh

# Enable 256-color and true-color (24-bit) support in tmux
set -g default-terminal "screen-256color" # Set terminal type for 256-color support
set -ga terminal-overrides ",*256col*:Tc" # Override to enable true-color for compatible terminals

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor'
# set -g @plugin "articicestudio/nord-tmux"

set -g set-clipboard on
set -g mode-keys vi
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 1000000
set -g mouse on
set -g status-interval 3
set -g allow-passthrough on

# Style
gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
cyan_soft="#88c0d0"
blue_muted="#81A1C1"
green_soft="#A3BE8C"

set -g base-index 1
set -g status-position top
set -g status-left-length 100
set -g status-style "fg=${gray_light},bg=default"
set -g status-left "#[fg=${green_soft},bold] #S #[fg=${gray_light},nobold] | "
set -g status-right " #{cpu}   #{mem} "
set -g window-status-current-format "#[fg=${cyan_soft},bold] #[underscore]#I:#W"
set -g window-status-format " #I:#W"
set -g message-style "fg=${gray_light},bg=default"
set -g mode-style "fg=${gray_dark},bg=${blue_muted}"
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${green_soft}"

# Resurrect
set -g @resurrect-capture-pane-contents 'on'

# Pane navigation without prefix
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Pane resize with prefix (Ctrl+b then Ctrl+hjkl)
bind C-h resize-pane -L 1
bind C-j resize-pane -D 1
bind C-k resize-pane -U 1
bind C-l resize-pane -R 1

# Keyboard-first copy mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
