[colors.primary]
background = '#101216'
foreground = '#E2E5EB'

[colors.selection]
text = '#E2E5EB'
background = '#394058'

[colors.cursor]
text = '#FFFFFF'
cursor = '#69749A'

[colors.normal]
black   = '#808080'
red     = '#D75F5F'
green   = '#5FAF5F'
yellow  = '#D7AF5F'
blue    = '#5F87D7'
magenta = '#AF87D7'
cyan    = '#6EA0AA'
white   = '#D0D0D0'

[colors.bright]
black   = '#8A8A8A'
red     = '#FF7777'
green   = '#87D787'
yellow  = '#FFD75F'
blue    = '#87AFFF'
magenta = '#D7AFFF'
cyan    = '#86B8C2'
white   = '#F5F5F5'
