[colors.primary]
background = '#121414'
foreground = '#e3e2e2'

[colors.selection]
text = '#e3e2e2'
background = '#39494c'

[colors.cursor]
text = '#121414'
cursor = '#b8cacd'

[colors.normal]
black   = '#121414'
red     = '#eb6a96'
green   = '#66cd70'
yellow  = '#fff572'
blue    = '#aabfc2'
magenta = '#4d5c5e'
cyan    = '#b8cacd'
white   = '#cad5d7'

[colors.bright]
black   = '#7b8485'
red     = '#ff9fc0'
green   = '#9ff6a8'
yellow  = '#fff8a5'
blue    = '#cddee1'
magenta = '#ecfcff'
cyan    = '#f3fdff'
white   = '#f8feff'
