[colors.primary]
background = '#08090b'
foreground = '#e2e5eb'

[colors.selection]
text = '#e2e5eb'
background = '#394058'

[colors.cursor]
text = '#08090b'
cursor = '#69749a'

[colors.normal]
black   = '#111318'
red     = '#c7637c'
green   = '#4d9a59'
yellow  = '#c0bb56'
blue    = '#7580ae'
magenta = '#8b7bb8'
cyan    = '#69749A'
white   = '#979aa1'

[colors.bright]
black   = '#77797f'
red     = '#cf8196'
green   = '#78b882'
yellow  = '#e6e396'
blue    = '#7b85a9'
magenta = '#9ba5c8'
cyan    = '#b8bfd7'
white   = '#d9dbdf'
